// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwnnz1bo7tBFiv1q9ABXZpH7EhIojJF8k',
    appId: '1:528029530340:web:8c74809a3af9e0a80714f1',
    messagingSenderId: '528029530340',
    projectId: 'insta-clone-e7d75',
    authDomain: 'insta-clone-e7d75.firebaseapp.com',
    storageBucket: 'insta-clone-e7d75.appspot.com',
    measurementId: 'G-7M199BJNVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr5X32yq7gYqL-rqNVM9Q7chdf75Jo-Tg',
    appId: '1:528029530340:android:80ac4a29fa1cff170714f1',
    messagingSenderId: '528029530340',
    projectId: 'insta-clone-e7d75',
    storageBucket: 'insta-clone-e7d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVmg4KdRmUIo0DLKLR4jNcPw3iBp5OdJk',
    appId: '1:528029530340:ios:25e927297d9ace750714f1',
    messagingSenderId: '528029530340',
    projectId: 'insta-clone-e7d75',
    storageBucket: 'insta-clone-e7d75.appspot.com',
    androidClientId: '528029530340-56d04ee79mo81hdouh77728ja0u87r3j.apps.googleusercontent.com',
    iosClientId: '528029530340-pjqihc6o7kqd04lfenm6a4cscnnltiho.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVmg4KdRmUIo0DLKLR4jNcPw3iBp5OdJk',
    appId: '1:528029530340:ios:4d55afb4015c0e930714f1',
    messagingSenderId: '528029530340',
    projectId: 'insta-clone-e7d75',
    storageBucket: 'insta-clone-e7d75.appspot.com',
    androidClientId: '528029530340-56d04ee79mo81hdouh77728ja0u87r3j.apps.googleusercontent.com',
    iosClientId: '528029530340-ltd8auq4kmv4qedhr5i4iu9euanou0d7.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaApp.RunnerTests',
  );
}
